#!/bin/sh

#echo To start web interface, run:
path=`readlink -e $0`
base=`dirname $path`
executable=python
type python2.6 >/dev/null 2>&1 && executable=python2.6
export PYTHONPATH=.. 
$executable $base/controller.py
