#!/bin/bash

# kill any python processes running the controller or proxy

PID=`ps -C python,python2.6 -o pid,args \
	| egrep "python.*(controller|proxy).py$"\
	| sed 's/ *\([0-9]\+\) \+.*/\1/'`
if [ "$PID" ]
then
	kill $PID
else
	echo No processes found
fi
