#!/bin/sh
test -d ../scripts && cd ..
test -x scripts/mk || (echo mk run from inappropriate directory; exit 1)
PWD=`pwd`
PATH=$PWD/scripts:$PATH export PATH
build_makefile "$@" > Makefile
TARGET=`make echo_target`
PATH=$PWD/$TARGET:$PATH export PATH
PROCESSES=$((`ls -d /sys/devices/system/cpu/cpu[0-9]* | wc -l`+1))
make --jobs=$PROCESSES "$@"
