#!/usr/bin/env python

# parse the config file and output it in a format readable for shell scripts

import sys
from bowerbird.configobj import ConfigObj
from optparse import OptionParser

# location of configuration file
DEFAULT_CONFIG_FILE = '../bowerbird_config'
DEFAULT_OUTPUT_FILE = "/dev/stdout"
SH_SEPARATOR = '__'

# parse commandline options
parser = OptionParser()
parser.add_option("-c", "--config", dest="config_file", 
		help="configuration file to convert", default=DEFAULT_CONFIG_FILE)
parser.add_option("-o", "--output", dest="output_file",
		help="file to write shell variables", 
		default=DEFAULT_OUTPUT_FILE)
(options, args) = parser.parse_args()

# open configuration file
config = ConfigObj(options.config_file)

output = file(options.output_file, "w")

# print preamble
output.write('''# global variables automatically generated by %s
# from '%s' to permit easy access for shell scripts

# Do not edit directly as it will be overwritten
''' % (sys.argv[0], options.config_file))

# read station information
for section in config:
	if section != "dummy":
		output.write("\n# Section %s:\n" % section)
		for key in config[section]:
			output.write("%s%s%s=\"%s\"\n" % (section, SH_SEPARATOR, key, 
					config[section][key]))
